import "../styles/globals.css";
import Header from "./Header";
import Providers from "./Providers";

export const metadata = {
  title: "The LIVE News",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* <head/> */}
      <body className="bg-gray-100 dark:bg-slate-800 transition-all duration-700">
        <Providers>
          <Header />
          <div className="max-w-6xl mx-auto">{children}</div>
        </Providers>
      </body>
    </html>
  );
}
